export default {
    sheetData: {
        range: "'Form Responses 1'!A1:BM124",
        majorDimension: 'ROWS',
        values: [
            [
                'Timestamp',
                "What's your gender?",
                'How old are you?',
                'On average, how often do you check your e-mail each day?',
                'Which smartphone operating system do you use?',
                'You use little helpers to keep you concentrated. ',
                'You are usually highly motivated and energetic.',
                'In general, you would like to spend less time on your phone.',
                'You have no problem staying undistracted on a task for longer periods (~60 minutes). ',
                'You try to respond to your e-mails as soon as possible and cannot stand a messy inbox.',
                'When you wake up, you check your phone first thing in the morning.',
                'You have a morning ritual to start the day.',
                'I set weekly/daily goals.',
                'You regularly talk about your goals with friends.',
                'You have remarkable willpower.',
                'You often get so lost in thoughts that you ignore or forget your surroundings.',
                'You have trouble sleeping through the night.',
                "You have no trouble getting back to work after You'­ve been interrupted.",
                "You find that even though you schedule time, you don't actually accomplish very much.",
                'You can drink caffeine right before bedtime and still go to sleep.',
                'When you really need to concentrate, you can tune out your environment.',
                'You try to do certain activities at the same time and in the same place every day.',
                'You actively look for study partners who will help you stay focused on your work and your goals.',
                'You share accomplishments with friends or family.',
                'You use social media to share accomplishments.',
                'You frequently try new approaches to stay more focused or productive.',
                'I have found the "Screen Time" option on my phone',
                'What was your overall screen time over the last week?',
                'Over the last 7 days, what were your 6 most used apps? ',
                'How many total pickups/phone unlocks?',
                'What were the 4 first used apps after a pickup? ',
                'How many notifications did you get in total?',
                'What were the 4 apps with the most notifications?',
                'Did the data surprise you?',
                'Did you ever inform yourself about methods that promise to spend less time on your devices?',
                'Did you ever try any of those methods? [Put the phone on flight mode]',
                'Did you ever try any of those methods? [Put the phone in another room]',
                'Did you ever try any of those methods? [Disable notifications on certain apps]',
                'Did you ever try any of those methods? [Plan specific times to use the phone during the day]',
                'Did you ever try any of those methods? [Turn off WIFI]',
                'Did you ever try any of those methods? [Delete apps that distract too much]',
                'Did you ever try any of those methods? [Delete Facebook]',
                'Did you ever try any of those methods? [Delete Instagram]',
                'Did you ever try any of those methods? [Plan specific times to check mail during the day]',
                'Did you ever try any of those methods? [Carefully plan each day using my calendar]',
                'Which methods did you try not listed above?',
                'How successful were those methods?',
                'Where did you get those methods from?',
                'At which average time do you wake up each day?',
                'When do you plan your Calendar Events? [Before Monday]',
                'When do you plan your Calendar Events? [In the evening before]',
                'When do you plan your Calendar Events? [In the morning]',
                "When do you plan your Calendar Events? [I don't have a schedule for writing down my TODOs]",
                'How frequently do you write down your TODOs / Events using the following methods? [Pen & Paper Calendar ]',
                'How frequently do you write down your TODOs / Events using the following methods? [Todo App]',
                'How frequently do you write down your TODOs / Events using the following methods? [Calendar App]',
                'How frequently do you write down your TODOs / Events using the following methods? [Notes App]',
                'How frequently do you write down your TODOs / Events using the following methods? [Reminders App]',
                'How frequently do you write down your TODOs / Events using the following methods? [Pen & Paper Todo List]',
                'How frequently do you write down your TODOs / Events using the following methods? [Other]',
                'If you chose "Other", which methods do you use?',
                'Do you think, you spend a lot of time on your phone that could be spend better on other activities?',
                'In which situations do you use a shared calendar? ',
                'What is your current profession?',
                'Interested in the survey results? Leave your email here.',
            ],
            [
                '3/11/2019 12:51:19',
                '👨‍🦰Male',
                '25-30 years old',
                '9 - 14',
                'iOS',
                '2',
                '3',
                '4',
                '5',
                '4',
                '3',
                '2',
                '1',
                '1',
                '5',
                '3',
                '1',
                '4',
                '1',
                '2',
                '5',
                '1',
                '1',
                '3',
                '1',
                '1',
                '👍 Yes',
                '1:13',
                'WhatsApp, Safari, Slack, Mail, LinkedIn, Signal',
                '66',
                'WhatsApp, Signal, Safari, Mail',
                '606',
                'WhatsApp, Signal, Mail, Slack',
                '5',
                '👎 No',
                'Tried and worked',
                'Tried and worked',
                'Tried and worked',
                'Never tried',
                'Never tried',
                'Tried and worked',
                'Tried and worked',
                'Tried and worked',
                'Never tried',
                'Tried and worked',
                '',
                '5',
                '',
                '6 - 7 am',
                '👎 No',
                '👎 No',
                '👎 No',
                '👍 Yes',
                'Never',
                'Never',
                'Each day',
                'Never',
                'Never',
                'Never',
                'Never',
                '',
                '2',
                'Work, Personal Projects',
                'Student',
            ],
            [
                '3/11/2019 18:51:35',
                '👨‍🦰 Male',
                '18-24 years old',
                "I don't check daily",
                'Android',
                '3',
                '5',
                '5',
                '2',
                '',
                '',
                '5',
                '4',
                '4',
                '5',
                '4',
                '1',
                '4',
                '',
                '4',
                '',
                '',
                '1',
                '',
                '',
                '',
                '👍 Yes',
                '',
                '',
                '',
                '',
                '1399',
                '',
                '3',
                '👎 No',
                'Tried and worked',
                'Never tried',
                'Tried and worked',
                'Tried and worked',
                'Never tried',
                'Tried and worked',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                '',
                '4',
                'Friends',
                '',
                '',
                '',
                '',
                '',
                'Each day',
                'Never',
                '1 + per week',
                '5 + per week',
                'Never',
                '5 + per week',
                'Never',
                '',
                '5',
                "I don't use shared calendars",
                'Soldier ',
            ],
            [
                '3/11/2019 19:16:06',
                '👩 Female',
                '18-24 years old',
                '15+',
                'Android',
                '1',
                '3',
                '4',
                '3',
                '5',
                '5',
                '4',
                '2',
                '1',
                '2',
                '5',
                '5',
                '4',
                '5',
                '3',
                '3',
                '2',
                '4',
                '4',
                '3',
                '2',
                '👍 Yes',
                '33:45',
                'Instagram, Whatsapp, Tinder, Anruf, Facebook Messenger, YouTube ',
                '925',
                'Whatsapp: 300, Tinder:81, Instagram: 134, Anruf: 34',
                '2000',
                'Tinder: 600, Facebook: 80, Instagram: 50, LinkedIn: 15',
                '4',
                '👎 No',
                'Tried and worked',
                'Tried and worked',
                'Tried and worked',
                'Never tried',
                'Never tried',
                'Tried and worked',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                '-',
                '',
                '',
                '7 - 8 am',
                '😐 Sometimes',
                '👎 No',
                '👎 No',
                '😐 Sometimes',
                'Never',
                'Never',
                'Never',
                'Never',
                'Never',
                '1 + per week',
                'Never',
                '',
                '5',
                "I don't use shared calendars",
                'Intern',
                'Ana.keser@web.de',
            ],
            [
                '3/11/2019 19:21:00',
                '👨‍🦰 Male',
                '18-24 years old',
                "I don't check daily",
                'iOS',
                '5',
                '5',
                '5',
                '3',
                '3',
                '2',
                '4',
                '5',
                '5',
                '4',
                '4',
                '1',
                '3',
                '2',
                '5',
                '4',
                '3',
                '2',
                '4',
                '2',
                '3',
                '👍 Yes',
                '3.06',
                'Whatsapp_one\nYouTube_two\nNotes_three\nSpotify_four\nPhone_five\nPhotos_six\nGoogle_seven',
                '88',
                'Whatsapp_190\nSpotify_45\nPhone_30\nPhotos_27',
                '145',
                'Clock_42\nHeadspace_21\nGmail_20\nMaps_10',
                '3',
                '👍 Yes',
                'Tried and worked',
                'Tried and worked',
                'Tried and worked',
                'Never tried',
                'Never tried',
                'Tried and worked',
                'Tried and worked',
                'Tried and worked',
                'Never tried',
                'Tried and worked',
                'Limiting my time for each task to work more efficiently with a deadline ',
                '5',
                'Books, Friends, Audiobook, YouTube',
                '6 - 7 am',
                '👍 Yes',
                '👍 Yes',
                '😐 Sometimes',
                '👎 No',
                'Never',
                'Never',
                'Each day',
                'Each day',
                'Never',
                '1 + per week',
                'Never',
                '',
                '5',
                "I don't use shared calendars",
                'Coach',
                'yegani777@gmail.com',
            ],
            [
                '3/11/2019 20:30:53',
                '👩 Female',
                '25-30 years old',
                '5 - 8',
                'iOS',
                '2',
                '2',
                '3',
                '1',
                '4',
                '5',
                '2',
                '3',
                '4',
                '4',
                '1',
                '5',
                '3',
                '2',
                '2',
                '3',
                '1',
                '4',
                '5',
                '1',
                '2',
                '👍 Yes',
                '14:10',
                'YouTube, Instagram, WhatsApp, Safari, Snapchat, Phone',
                '138',
                'WhatsApp, Instagram, YouTube, Safari',
                '1280',
                'WhatsApp:1001, Instagram:169, Gmail:28, Messages:21',
                '5',
                '👎 No',
                'Tried and worked',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                'Tried and worked',
                'Tried and did not work',
                'Never tried',
                'Never tried',
                '',
                '',
                '',
                '6 - 7 am',
                '😐 Sometimes',
                '👎 No',
                '😐 Sometimes',
                '👍 Yes',
                '5 + per week',
                'Never',
                '1 + per week',
                '1 + per week',
                'Never',
                'Never',
                '5 + per week',
                '',
                '4',
                'Work',
                'Student',
                'laura.reshani@gmail.com',
            ],
            [
                '3/11/2019 21:07:51',
                '👩 Female',
                '25-30 years old',
                '5 - 8',
                'iOS',
                '3',
                '5',
                '4',
                '2',
                '4',
                '5',
                '2',
                '4',
                '3',
                '3',
                '4',
                '3',
                '2',
                '5',
                '4',
                '2',
                '4',
                '5',
                '5',
                '1',
                '2',
                '👎 No, I will answer the questions with my gut feeling',
                '12 hours ',
                'WhatsApp, Instagram, Facebook, imusic, Snapchat, ted ',
                '',
                'Instagram, snapchat, Facebook, ',
                '15',
                'Facebook:5, Instagram:4, snap:6 ',
                '2',
                '👎 No',
                'Tried and did not work',
                'Never tried',
                'Never tried',
                'I want to try',
                'Tried and did not work',
                'Tried and worked',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                '',
                '2',
                '',
                '',
                '😐 Sometimes',
                '👎 No',
                '👎 No',
                '👍 Yes',
                '5 + per week',
                'Never',
                'Each day',
                'Never',
                'Never',
                'Never',
                'Never',
                '',
                '5',
                "I don't use shared calendars",
                'Student',
            ],
            [
                '3/11/2019 22:07:01',
                '👨‍🦰 Male',
                '18-24 years old',
                '5 - 8',
                'iOS',
                '3',
                '6',
                '3',
                '5',
                '3',
                '4',
                '4',
                '5',
                '4',
                '4',
                '3',
                '1',
                '5',
                '2',
                '4',
                '5',
                '4',
                '2',
                '5',
                '5',
                '3',
                '👎 No, I will answer the questions with my gut feeling',
                '10:00',
                'Instagram, WhatsApp, Facebook, GMX, Grindr, Spotify',
                '300',
                'Don’t know',
                '500',
                'Whatsapp, Instagram, GMX, Grindr',
                '3',
                '👎 No',
                'Tried and worked',
                'Never tried',
                'Tried and worked',
                'Tried and worked',
                'Never tried',
                'Tried and worked',
                'Tried and worked',
                'Tried and worked',
                'Never tried',
                'Never tried',
                '',
                '3',
                'Friends',
                '7 - 8 am',
                '',
                '👍 Yes',
                '',
                '',
                '5 + per week',
                'Never',
                'Never',
                'Never',
                'Never',
                '5 + per week',
                'Never',
                '',
                '3',
                'Work, Personal Projects',
                'Composer',
            ],
            [
                '3/11/2019 22:07:45',
                '👩 Female',
                '18-24 years old',
                '2 - 4',
                'iOS',
                '2',
                '5',
                '5',
                '4',
                '4',
                '4',
                '5',
                '4',
                '3',
                '4',
                '2',
                '2',
                '4',
                '2',
                '3',
                '5',
                '2',
                '2',
                '5',
                '2',
                '4',
                '👍 Yes',
                '6:10',
                'Instagram, WhatsApp, YouTube ',
                '22',
                '',
                '642',
                'WhatsApp:334, Snapchat:116, Mail:80, Instagram:54',
                '5',
                '👍 Yes',
                'Tried and worked',
                'Never tried',
                'Never tried',
                'Tried and worked',
                'Never tried',
                'Never tried',
                'I want to try',
                'I want to try',
                'I want to try',
                'Tried and worked',
                '',
                '4',
                'Books, YouTube',
                '6 - 7 am',
                '👍 Yes',
                '😐 Sometimes',
                '👎 No',
                '👎 No',
                '1 + per week',
                'Never',
                '5 + per week',
                'Each day',
                'Never',
                '5 + per week',
                'Never',
                '',
                '5',
                "I don't use shared calendars",
                'Primary teacher student',
            ],
            [
                '3/11/2019 22:50:07',
                '👩 Female',
                '18-24 years old',
                '2 - 4',
                'iOS',
                '4',
                '6',
                '5',
                '5',
                '1',
                '1',
                '5',
                '5',
                '5',
                '5',
                '2',
                '1',
                '4',
                '3',
                '4',
                '5',
                '4',
                '3',
                '5',
                '3',
                '4',
                '👍 Yes',
                '3:52',
                'WhatsApp, Instagram, Spotify ',
                '632',
                'WhatsApp:100, Telefon:19, Instagram:16, Spotify:11',
                '817',
                'WhatsApp:461, Erinnerungen:76, Instagram:51, Kalender:30',
                '3',
                '👍 Yes',
                'Tried and worked',
                'Never tried',
                'Tried and worked',
                'Tried and worked',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                'I want to try',
                'I want to try',
                '- Go to a place where focussed ppl are around (feeling of being supervised)',
                '5',
                'University, Prior company I worked for  ',
                '6 - 7 am',
                '👍 Yes',
                '👎 No',
                '😐 Sometimes',
                '👎 No',
                'Each day',
                '1 + per week',
                '1 + per week',
                '1 + per week',
                '5 + per week',
                '5 + per week',
                'Never',
                '',
                '3',
                'Work',
                'Freelancer',
                'vienne08@hotmail.de',
            ],
            [
                '3/11/2019 23:04:41',
                '👨‍🦰 Male',
                '18-24 years old',
                '2 - 4',
                'Android',
                '4',
                '4',
                '4',
                '5',
                '2',
                '5',
                '5',
                '3',
                '3',
                '3',
                '4',
                '3',
                '3',
                '3',
                '2',
                '5',
                '3',
                '3',
                '5',
                '3',
                '3',
                '👍 Yes',
                '3:44',
                'Hill Climb Racing, Chrome, YouTube Music, WhatsApp, Telegram, 9gag',
                '451',
                'WhatsApp:188, Chrome:97, YT Music:90, Google:101',
                '930',
                'WhatsApp:415, Google:115, Telegram:148, YT Music:105',
                '2',
                '👍 Yes',
                'Tried and worked',
                'Never tried',
                'Never tried',
                'Never tried',
                'Tried and worked',
                'Still trying',
                'I want to try',
                'I want to try',
                'Never tried',
                'Tried and did not work',
                'Turn phone off, switch phone to night light mode, use android shush mode, go somewhere else and leave phone at home ',
                '4',
                'Apps, YouTube, My own ingenuity',
                '8 - 9 am',
                '👎 No',
                '😐 Sometimes',
                '😐 Sometimes',
                '👍 Yes',
                'Never',
                '1 + per week',
                '5 + per week',
                '1 + per week',
                '1 + per week',
                '1 + per week',
                'Never',
                '',
                '5',
                'Work',
                'Design student',
            ],
            [
                '3/11/2019 23:57:58',
                '👨‍🦰 Male',
                '25-30 years old',
                '2 - 4',
                'iOS',
                '2',
                '4',
                '5',
                '4',
                '5',
                '4',
                '5',
                '2',
                '2',
                '4',
                '3',
                '2',
                '2',
                '2',
                '4',
                '5',
                '1',
                '4',
                '2',
                '1',
                '4',
                '👎 No, I will answer the questions with my gut feeling',
                '7:00',
                'Telegram, WhatsApp, Spotify, Google Mail, Outlook, Chrome',
                '83',
                'WhatsApp:35, Telegram:32, Chrome:13, Google Mail: 3',
                '25',
                'WhatsApp: 18, Telegram: 6, Google Mail: 1',
                '1',
                '👍 Yes',
                'Tried and worked',
                'Tried and worked',
                'Tried and worked',
                'Tried and did not work',
                'Tried and worked',
                'Tried and worked',
                'Tried and worked',
                'Tried and worked',
                'Never tried',
                'Tried and worked',
                'Turn the phone to greyscale for it to be less attractive',
                '4',
                'Website',
                '8 - 9 am',
                '😐 Sometimes',
                '👍 Yes',
                '👎 No',
                '👍 Yes',
                'Never',
                '5 + per week',
                '1 + per week',
                'Never',
                '1 + per week',
                '5 + per week',
                'Never',
                '',
                '2',
                'Work, University ',
                'Interface designer',
                'contact@vogelino.com',
            ],
            [
                '3/12/2019 4:59:09',
                '👨‍🦰 Male',
                '25-30 years old',
                '2 - 4',
                'iOS',
                '4',
                '5',
                '3',
                '3',
                '3',
                '2',
                '5',
                '5',
                '5',
                '4',
                '3',
                '1',
                '2',
                '3',
                '2',
                '4',
                '4',
                '5',
                '5',
                '2',
                '5',
                '👍 Yes',
                '20:51',
                'Google maps, musik, safari, uhr, whatsapp',
                '508',
                'Google maps, whatsapp, Notizen, MyWährung ',
                '169',
                'Uhr, instagram, Kalender, Telefon ',
                '3',
                '👎 No',
                'Tried and worked',
                'Never tried',
                'Tried and worked',
                'Still trying',
                'Tried and did not work',
                'Tried and worked',
                'Never tried',
                'Never tried',
                'Tried and did not work',
                'Still trying',
                '',
                '3',
                'Books, Friends, Apps, Audiobook, Website',
                '6 - 7 am',
                '😐 Sometimes',
                '😐 Sometimes',
                '😐 Sometimes',
                '👍 Yes',
                'Never',
                'Never',
                'Never',
                'Never',
                'Never',
                '5 + per week',
                'Never',
                '',
                '4',
                'Work, Home, Personal Projects',
                'Salesmanager',
                'cleym@web.de',
            ],
            [
                '3/12/2019 8:54:49',
                '👩 Female',
                '18-24 years old',
                '1',
                'Android',
                '1',
                '4',
                '5',
                '5',
                '3',
                '5',
                '1',
                '1',
                '1',
                '5',
                '4',
                '5',
                '5',
                '1',
                '1',
                '5',
                '5',
                '5',
                '5',
                '1',
                '1',
                '👎 No, I will answer the questions with my gut feeling',
                '3h and 42 minutes',
                'Instagram,  WhatsApp, Spotify, Chrome, Google Tables',
                '60',
                '',
                '',
                'Spotify:45; Instagram:39; WhatsApp: 27; Chrome: 9',
                '4',
                '👎 No',
                'Tried and worked',
                'Tried and worked',
                'Tried and did not work',
                'Never tried',
                'Tried and worked',
                'Tried and worked',
                'Tried and worked',
                'Never tried',
                'Never tried',
                'Never tried',
                'taking a smartphone break and using a regular mobile phone for calls only for about 2 months',
                '4',
                'Friends',
                '7 - 8 am',
                '😐 Sometimes',
                '👎 No',
                '👎 No',
                '👍 Yes',
                '1 + per week',
                'Never',
                'Never',
                'Never',
                'Never',
                '1 + per week',
                'Never',
                '',
                '5',
                "I don't use shared calendars",
                'Student ',
            ],
            [
                '3/12/2019 10:18:26',
                '👩 Female',
                '25-30 years old',
                '5 - 8',
                'iOS',
                '3',
                '4',
                '4',
                '3',
                '5',
                '5',
                '1',
                '4',
                '5',
                '3',
                '5',
                '2',
                '3',
                '3',
                '1',
                '5',
                '2',
                '4',
                '5',
                '1',
                '3',
                '👍 Yes',
                '14h 16m',
                'WhatsApp, Facebook, Telegram, Safari, Photos & Deezer',
                '144',
                'Whatsapp, Deezer, Mail & Facebook',
                '687',
                'Whatsapp, Outlook, ImmoScout & Clock',
                '5',
                '👎 No',
                'Tried and worked',
                'Tried and worked',
                'Tried and worked',
                'Never tried',
                'Tried and worked',
                'Tried and worked',
                'Never tried',
                'Tried and worked',
                'Never tried',
                'Never tried',
                '',
                '4',
                '',
                '7 - 8 am',
                '',
                '👎 No',
                '',
                '',
                'Never',
                'Never',
                'Each day',
                'Never',
                'Never',
                'Each day',
                'Never',
                '',
                '5',
                'Work, Home',
                'Junior Marketing Manager & Master Student',
            ],
            [
                '3/12/2019 11:43:03',
                '👨‍🦰 Male',
                '18-24 years old',
                '1',
                'iOS',
                '2',
                '4',
                '4',
                '4',
                '5',
                '5',
                '1',
                '3',
                '1',
                '4',
                '4',
                '2',
                '5',
                '2',
                '5',
                '5',
                '2',
                '1',
                '5',
                '3',
                '2',
                '👍 Yes',
                '16:55',
                'Facebook,Whatsapp,Youtube,Safari,Spotify,Clash Royale',
                '525',
                'Whatsapp:129, Fotmob:26,Spotify:23, Safari:19',
                '686',
                'Whatsapp: 560, Snapchat: 70, 1&1 Mail:17, Uhr:15',
                '4',
                '👎 No',
                'Tried and worked',
                'Never tried',
                'I want to try',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                '',
                '4',
                'Friends',
                '8 - 9 am',
                '😐 Sometimes',
                '👎 No',
                '😐 Sometimes',
                '👍 Yes',
                'Never',
                'Never',
                'Never',
                'Never',
                'Never',
                'Never',
                'Never',
                '',
                '5',
                "I don't use shared calendars",
                'Sports student',
            ],
            [
                '3/12/2019 12:06:14',
                '👩 Female',
                '12-17 years old',
                '1',
                'iOS',
                '5',
                '3',
                '4',
                '2',
                '2',
                '5',
                '4',
                '3',
                '2',
                '3',
                '3',
                '3',
                '4',
                '2',
                '4',
                '4',
                '4',
                '3',
                '5',
                '3',
                '2',
                '👍 Yes',
                '25:15',
                'WhatsApp, Instagram, YouTube, Safari, Facebook, Snapchat',
                '1015',
                'WhatsApp:372, Instagram:43, Snapchat:38, Safari:16',
                '1667',
                'WhatsApp:1444, Snapchat:122, Messenger:16, Erinnerungen:14',
                '4',
                '👎 No',
                'Never tried',
                'Tried and worked',
                'Never tried',
                'Never tried',
                'Never tried',
                'I want to try',
                'I want to try',
                'I want to try',
                'Never tried',
                'Never tried',
                'Placing mobile out of sight, using mobile as a rewarding after getting something done ',
                '4',
                'My own idea ',
                '6 - 7 am',
                '😐 Sometimes',
                '👎 No',
                '👎 No',
                '👍 Yes',
                'Never',
                'Never',
                'Never',
                '1 + per week',
                'Each day',
                '1 + per week',
                'Never',
                '',
                '4',
                'Work',
                'Student',
                'ameliebergler@online.de',
            ],
            [
                '3/12/2019 12:44:09',
                '👩 Female',
                '25-30 years old',
                '2 - 4',
                'iOS',
                '2',
                '5',
                '3',
                '5',
                '3',
                '5',
                '5',
                '5',
                '3',
                '4',
                '2',
                '2',
                '4',
                '3',
                '4',
                '5',
                '5',
                '4',
                '5',
                '2',
                '3',
                '👍 Yes',
                '2:03',
                'Instagram_one, whatsapp_two, MyFitnessPal_three, kamera_four, Notizen_five, Fotos_six',
                '248',
                'Instagram_one:71, whatsapp_two:31, kamera_three:15, myfitnesspal_four:12 ',
                '195',
                'Instagram_one:108, WhatsApp_two:68, nachrichten_three:14, telefon_four:1',
                '2',
                '👎 No',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                'Tried and worked',
                'None ',
                '3',
                '',
                '6 - 7 am',
                '👍 Yes',
                '👎 No',
                '👎 No',
                '👎 No',
                'Each day',
                'Never',
                'Never',
                '1 + per week',
                'Never',
                'Each day',
                'Never',
                '',
                '3',
                'Work',
                'Project Manager',
            ],
            [
                '3/12/2019 13:13:42',
                '👩 Female',
                '18-24 years old',
                '2 - 4',
                'iOS',
                '3',
                '3',
                '2',
                '5',
                '2',
                '1',
                '4',
                '',
                '5',
                '4',
                '1',
                '1',
                '4',
                '',
                '4',
                '',
                '2',
                '2',
                '3',
                '3',
                '3',
                '👍 Yes',
                '1:14',
                'whatsapp,spotify,facebook,instagram',
                '156',
                'whatsapp:96,facebook:3,instagram:32,spotify:24',
                '',
                '',
                '1',
                '👎 No',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                '',
                '',
                '',
                '4 - 6 am',
                '👎 No',
                '',
                '',
                '',
                'Never',
                'Never',
                'Never',
                'Never',
                'Never',
                'Never',
                'Never',
                '',
                '1',
                "I don't use shared calendars",
                'tax assistant',
            ],
            [
                '3/12/2019 13:18:36',
                '👩 Female',
                '18-24 years old',
                '1',
                'iOS',
                '2',
                '3',
                '2',
                '4',
                '1',
                '1',
                '5',
                '2',
                '1',
                '3',
                '5',
                '1',
                '2',
                '3',
                '5',
                '3',
                '5',
                '1',
                '3',
                '1',
                '3',
                '👎 No, I will answer the questions with my gut feeling',
                '10 Hours and 33 minutes',
                'WhatsApp, YouTube, asos, Pinterest, Quiz duell',
                '5',
                'WhatsApp 33, Pinterest 5, asos 3, YouTube 3',
                '33',
                'WhatsApp 18, YouTube 13, Pinterest 10, asos 3',
                '3',
                '👎 No',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                'Tried and worked',
                'Never tried',
                'Never tried',
                'Never tried',
                '',
                '3',
                'Parents, YouTube',
                '6 - 7 am',
                '😐 Sometimes',
                '😐 Sometimes',
                '👎 No',
                '😐 Sometimes',
                'Never',
                '1 + per week',
                'Never',
                'Never',
                'Never',
                'Never',
                '1 + per week',
                '',
                '1',
                'Work',
                'Trainee ',
            ],
            [
                '3/12/2019 14:36:36',
                '👩 Female',
                '18-24 years old',
                '2 - 4',
                'iOS',
                '4',
                '6',
                '3',
                '2',
                '4',
                '4',
                '4',
                '5',
                '5',
                '4',
                '3',
                '5',
                '2',
                '3',
                '5',
                '4',
                '4',
                '4',
                '5',
                '5',
                '5',
                '👍 Yes',
                '1:12',
                'Instagram, Spotify, WhatsApp, Audible, GoogleMaps, GuitarTuna',
                '78',
                'WhatsApp:320, Instagram:123, YahooMail:92, Nachrichten:43',
                '674',
                '',
                '4',
                '👎 No',
                'Never tried',
                'Still trying',
                'Tried and worked',
                'Never tried',
                'Tried and worked',
                'Tried and worked',
                'Tried and worked',
                'Never tried',
                'Never tried',
                'Never tried',
                '',
                '3',
                'Friends, Website',
                '6 - 7 am',
                '👍 Yes',
                '👎 No',
                '😐 Sometimes',
                '👎 No',
                'Each day',
                '1 + per week',
                'Never',
                'Never',
                'Never',
                'Never',
                'Never',
                '',
                '3',
                'Home, Personal Projects',
                'Student',
            ],
            [
                '3/12/2019 14:44:59',
                '👩 Female',
                '18-24 years old',
                '1',
                'iOS',
                '2',
                '3',
                '4',
                '5',
                '5',
                '5',
                '4',
                '1',
                '1',
                '2',
                '2',
                '1',
                '1',
                '3',
                '1',
                '4',
                '2',
                '1',
                '1',
                '3',
                '1',
                '👍 Yes',
                '8:25',
                'YouTube, WhatsApp, Gala, Sportschau, Snapchat, Spotify  ',
                '260',
                'WhatsApp:45, Snapchat:10, Fotos: 7, Kamera: 5',
                '395',
                'WhatsApp: 306, Snapchat:33, Gala: 24, Erinnerungen: 14 ',
                '2',
                '👎 No',
                'Never tried',
                'Tried and worked',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                '',
                '3',
                'Friends',
                '4 - 6 am',
                '👎 No',
                '😐 Sometimes',
                '👎 No',
                '😐 Sometimes',
                'Never',
                'Never',
                '1 + per week',
                'Never',
                'Never',
                'Never',
                'Never',
                '',
                '3',
                "I don't use shared calendars",
                'Dental assistent',
            ],
            [
                '3/12/2019 15:46:50',
                '👩 Female',
                '25-30 years old',
                '9 - 14',
                'iOS',
                '2',
                '5',
                '5',
                '2',
                '4',
                '5',
                '5',
                '5',
                '5',
                '3',
                '2',
                '2',
                '4',
                '2',
                '2',
                '4',
                '3',
                '4',
                '5',
                '2',
                '3',
                '👍 Yes',
                '1:31',
                'Instagram, WhatsApp, calculator, chrome, photos, Facebook ',
                '532',
                'Whatsapp:161, Instagram:88, calculator:32, google maps:16',
                '391',
                'Whatsapp:253, Instagram:56, messages:10, slack:10',
                '3',
                '👎 No',
                'Never tried',
                'Never tried',
                'Tried and worked',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                'Never tried',
                'Tried and worked',
                '',
                '',
                '',
                '7 - 8 am',
                '👍 Yes',
                '😐 Sometimes',
                '👎 No',
                '👎 No',
                'Never',
                '5 + per week',
                'Each day',
                'Each day',
                '1 + per week',
                'Never',
                'Never',
                '',
                '4',
                'Work',
                'Project manager',
            ],
            [
                '3/12/2019 16:41:41',
                '👨‍🦰 Male',
                '25-30 years old',
                "I don't check them, I get push notifications and depending how important they are I'll read them right away or later",
                'iOS',
                '2',
                '2',
                '4',
                '1',
                '5',
                '5',
                '3',
                '3',
                '2',
                '2',
                '4',
                '2',
                '3',
                '4',
                '1',
                '4',
                '4',
                '4',
                '4',
                '2',
                '3',
                '👍 Yes',
                '9:41',
                'Instagram, Telegram, Reddit, Snapchat, Whatsapp, Facebook',
                '696',
                'Telegram:99, Whatsapp:88, Sapchat:57, Google Maps:36',
                '2278',
                'Whatsapp:776, Telegram:598, Instagram:322, Snapchat:164',
                '3',
                '👎 No',
                'Tried and worked',
                'Never tried',
                'Tried and worked',
                'Never tried',
                'Never tried',
                'Never tried',
                'I want to try',
                'Never tried',
                'Never tried',
                'I want to try',
                '',
                '2',
                'Friends, Apps, Website',
                '8 - 9 am',
                '😐 Sometimes',
                '😐 Sometimes',
                '😐 Sometimes',
                '👍 Yes',
                'Never',
                'Never',
                '1 + per week',
                'Never',
                '5 + per week',
                '1 + per week',
                'Never',
                '',
                '4',
                'Work, Girlfriend, Travelpartners',
                'Design Student',
            ],
        ],
    },
}
